"use client";
import { useEffect, useRef, useState } from 'react';
import { RadioTower, ArrowUpRight, ArrowRight, Users, Crosshair, HeartPulse, Wrench, Volume2, VolumeX, Settings2, X, Copy, Check, Zap, Shield, CircleHelp, Link2, LoaderCircle, Target, LogOut, RotateCcw, Play, Maximize2, Minimize2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input as TextInput } from '@/components/ui/input';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Progress } from '@/components/ui/progress';
import { createState,addPlayer,startMission,step,snapshot,move,EMPTY_INPUT,COLORS,ROLE_NAMES,contextAction,EXTRACTION,type Input,type State,type Role,type Player } from './engine';
import { GameAudio } from './audio';
import { GameConnection,type Session,type LinkStatus } from './network';
import type { GameRenderer } from './renderer';

type Modal='help'|'settings'|'create'|'join'|'roadmap'|null;
type Mode='menu'|'solo'|'online';
const roles:[Role,typeof Crosshair,string,string][]=[['assault',Crosshair,'Быстрый огонь','Q · перегрузка оружия'],['medic',HeartPulse,'Лечение отряда','Q · восстановление здоровья'],['engineer',Wrench,'Быстрый ремонт','Q · электромагнитный импульс']];
const timeText=(t:number)=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
function makeAttract(){const s=createState(4309);addPlayer(s,'preview','ПИЛОТ','assault',0);s.players[0].x=5;s.players[0].z=6;s.players[0].angle=-2;return s;}
const initial=makeAttract();

export default function Game(){
 const canvas=useRef<HTMLCanvasElement>(null),overlay=useRef<HTMLCanvasElement>(null),renderer=useRef<GameRenderer|null>(null),audio=useRef<GameAudio|null>(null),connection=useRef<GameConnection|null>(null),world=useRef<State>(initial),myId=useRef('preview'),modeRef=useRef<Mode>('menu'),modalRef=useRef<Modal>(null),lastState=useRef(performanceNow()),input=useRef<Input>({...EMPTY_INPUT}),keys=useRef(new Set<string>()),pointer=useRef({x:0,y:0,set:false}),touch=useRef({x:0,z:0,fire:false}),seq=useRef(0),reduced=useRef(false);
 const [mode,setMode]=useState<Mode>('menu'),[state,setState]=useState<State>(initial),[modal,setModal]=useState<Modal>(null),[role,setRole]=useState<Role>('assault'),[name,setName]=useState('Пилот'),[code,setCode]=useState(''),[session,setSession]=useState<Session|null>(null),[status,setStatus]=useState<LinkStatus>('offline'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[renderError,setRenderError]=useState(''),[volume,setVolume]=useState(35),[quality,setQuality]=useState('high'),[reduceMotion,setReduceMotion]=useState(false),[copied,setCopied]=useState(false),[ping,setPing]=useState(0),[full,setFull]=useState(false),[touchUi,setTouchUi]=useState(false),[toast,setToast]=useState('');
 const localPlayer=state.players.find(p=>p.id===myId.current),running=state.phase==='active'||state.phase==='extract',ended=state.phase==='won'||state.phase==='lost';
 const isHost=state.host===myId.current,completed=state.relays.filter(r=>r.active).length;
 useEffect(()=>{modalRef.current=modal;if(modal){keys.current.clear();input.current={...EMPTY_INPUT};touch.current={x:0,z:0,fire:false};}},[modal]);
 useEffect(()=>{reduced.current=reduceMotion;},[reduceMotion]);
 useEffect(()=>{let alive=true,raf=0;audio.current=new GameAudio();
  try{const prefs=JSON.parse(localStorage.getItem('last-signal-preferences')||'{}');if(typeof prefs.volume==='number'){setVolume(prefs.volume);audio.current.setVolume(prefs.volume/100);}if(prefs.quality)setQuality(prefs.quality);setReduceMotion(prefs.motion??window.matchMedia('(prefers-reduced-motion: reduce)').matches);if(prefs.name)setName(prefs.name);}catch{}
  setTouchUi(window.matchMedia('(pointer: coarse)').matches);
  const room=new URLSearchParams(location.search).get('room');if(room&&/^[A-Z2-9]{6}$/.test(room)){setCode(room);setModal('join');}
  void import('./renderer').then(({GameRenderer})=>{if(!alive||!canvas.current)return;try{renderer.current=new GameRenderer(canvas.current);setReady(true);let prev=performance.now(),acc=0,ui=0,net=0;
   const loop=(now:number)=>{if(!alive)return;const dt=Math.min((now-prev)/1000,.06);prev=now;const s=world.current,playing=modeRef.current!=='menu'&&(s.phase==='active'||s.phase==='extract');
    const p=s.players.find(p=>p.id===myId.current);const k=keys.current;let x=Number(k.has('KeyD')||k.has('ArrowRight'))-Number(k.has('KeyA')||k.has('ArrowLeft')),z=Number(k.has('KeyS')||k.has('ArrowDown'))-Number(k.has('KeyW')||k.has('ArrowUp'));if(touch.current.x||touch.current.z){x=touch.current.x;z=touch.current.z;}const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}
    let aim=input.current.aim;if(p&&pointer.current.set){const point=renderer.current!.aim(pointer.current.x,pointer.current.y);aim=Math.atan2(point.z-p.z,point.x-p.x);}if(touch.current.fire&&p){const enemies=[...s.enemies].sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z));if(enemies[0])aim=Math.atan2(enemies[0].z-p.z,enemies[0].x-p.x);}
    input.current=modalRef.current?{...EMPTY_INPUT,seq:seq.current}:{...input.current,x,z,aim,fire:input.current.fire||touch.current.fire,interact:k.has('KeyE'),dash:k.has('Space')||k.has('ShiftLeft'),reload:k.has('KeyR'),skill:k.has('KeyQ'),seq:seq.current};
    if(modeRef.current==='solo'&&playing&&!modalRef.current){acc+=dt;let steps=0;while(acc>=1/60&&steps++<5){step(s,{[myId.current]:input.current},1/60);acc-=1/60;}}
    if(modeRef.current==='online'){net+=dt;if(net>=.09){seq.current++;input.current.seq=seq.current;connection.current?.send(input.current);net=0;}}
    let visual=s;if(modeRef.current==='online'&&playing&&p&&p.hp>0){visual={...s,players:s.players.map(q=>({...q}))};const predicted=visual.players.find(q=>q.id===myId.current)!;const elapsed=Math.min((now-lastState.current)/1000,.14);move(predicted,input.current.x*6.2*elapsed,input.current.z*6.2*elapsed);predicted.angle=aim;}
    renderer.current!.render(visual,dt,myId.current,modeRef.current==='menu',reduced.current);if(playing)audio.current?.events(s.events,myId.current);drawOverlay(overlay.current,renderer.current!,visual,myId.current,playing,pointer.current,modalRef.current!==null);
    ui+=dt;if(ui>.1){setState(snapshot(s));ui=0;}raf=requestAnimationFrame(loop);
   };raf=requestAnimationFrame(loop);
  }catch(err){console.error(err);setRenderError('Для игры нужен браузер с WebGL 2. Включите аппаратное ускорение и обновите страницу.');}}).catch(()=>setRenderError('Не удалось загрузить сцену. Проверьте соединение и обновите страницу.'));
  const keydown=(e:KeyboardEvent)=>{const tag=(e.target as HTMLElement)?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if(e.code==='Escape'){if(modeRef.current!=='menu'&&!modalRef.current)setModal('settings');return;}if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code)&&modeRef.current!=='menu'&&!modalRef.current)e.preventDefault();if(!modalRef.current)keys.current.add(e.code);};
  const keyup=(e:KeyboardEvent)=>keys.current.delete(e.code);const mouseup=()=>{input.current.fire=false;touch.current.fire=false;};const blur=()=>{keys.current.clear();input.current={...EMPTY_INPUT};touch.current={x:0,z:0,fire:false};if(modeRef.current==='solo'&&!modalRef.current)setModal('settings');};
  const visibility=()=>{if(document.hidden)blur();};const fullscreen=()=>setFull(!!document.fullscreenElement);
  window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('pointerup',mouseup);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);document.addEventListener('fullscreenchange',fullscreen);
  return()=>{alive=false;cancelAnimationFrame(raf);connection.current?.disconnect(false);renderer.current?.dispose();audio.current?.dispose();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('pointerup',mouseup);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);document.removeEventListener('fullscreenchange',fullscreen);};
 },[]);
 useEffect(()=>{audio.current?.setVolume(volume/100);renderer.current?.setQuality(quality);try{localStorage.setItem('last-signal-preferences',JSON.stringify({volume,quality,motion:reduceMotion,name}));}catch{}},[volume,quality,reduceMotion,name,ready]);
 function showToast(text:string){setToast(text);setTimeout(()=>setToast(''),3500);}
 function resetEvents(){if(renderer.current)renderer.current.eventCursor=0;if(audio.current)audio.current.cursor=0;seq.current=0;}
 function startSolo(){audio.current?.unlock();connection.current?.disconnect();connection.current=null;setSession(null);setError('');myId.current='solo';const s=createState(Math.floor(Math.random()*1e9),'solo');addPlayer(s,'solo',name,role,0);s.players[0].x=0;startMission(s);world.current=s;modeRef.current='solo';setMode('solo');setState(snapshot(s));setModal(null);resetEvents();}
 function exitMission(){connection.current?.disconnect();connection.current=null;if(session)try{sessionStorage.removeItem(`last-signal-${session.code}`);}catch{}setSession(null);world.current=makeAttract();myId.current='preview';modeRef.current='menu';setMode('menu');setState(snapshot(world.current));setModal(null);setError('');keys.current.clear();input.current={...EMPTY_INPUT};resetEvents();}
 async function connectRoom(join:boolean){if(busy)return;setBusy(true);setError('');audio.current?.unlock();try{let saved={};if(join)try{saved=JSON.parse(sessionStorage.getItem(`last-signal-${code}`)||'{}');}catch{}
  const response=await fetch(join?`/api/rooms/${code}/join`:'/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,role,...saved})});const data=await response.json() as Session & {error?:string};if(!response.ok)throw new Error(data.error||'Не удалось создать отряд.');const next=data as Session;
  connection.current?.disconnect(false);setSession(next);try{sessionStorage.setItem(`last-signal-${next.code}`,JSON.stringify({id:next.id,token:next.token}));}catch{}
  world.current=next.state;myId.current=next.id;modeRef.current='online';setMode('online');setState(snapshot(next.state));setModal(null);resetEvents();
  connection.current=new GameConnection(next,(s,latency)=>{if(s.t<world.current.t)resetEvents();world.current=s;lastState.current=performance.now();setPing(Math.min(latency,9999));},(link,reason)=>{setStatus(link);if(reason)setError(reason);else if(link==='online')setError('');});
 }catch(e){setError(e instanceof Error?e.message:'Не удалось установить связь.');}finally{setBusy(false);}}
 async function copyInvite(){if(!session)return;try{await navigator.clipboard.writeText(`${location.origin}/?room=${session.code}`);setCopied(true);setTimeout(()=>setCopied(false),2400);}catch{showToast(`Код отряда: ${session.code}`);}}
 function restart(){if(mode==='solo')startSolo();else{connection.current?.request('restart');setError('');}}
 function touchKey(key:string,held:boolean){if(held)keys.current.add(key);else keys.current.delete(key);}
 const fullscreen=()=>{if(document.fullscreenElement)void document.exitFullscreen().catch(()=>showToast('Полноэкранный режим недоступен.'));else void document.documentElement.requestFullscreen().catch(()=>showToast('Полноэкранный режим недоступен.'));};
 return <main className={`game-shell ${mode==='menu'?'is-menu':'is-playing'} ${reduceMotion?'reduce-motion':''}`}>
  <div className="scene"><canvas ref={canvas} aria-label="Игровая станция Кеплер-09" onPointerMove={e=>{pointer.current={x:e.clientX,y:e.clientY,set:e.pointerType==='mouse'};}} onPointerDown={e=>{if(e.button===0&&mode!=='menu'&&running&&!modal){audio.current?.unlock();input.current.fire=true;}}} onContextMenu={e=>e.preventDefault()}/><canvas ref={overlay} className="scene-overlay" aria-hidden="true"/></div>
  <div className="vignette"/><div className="menu-shade"/>
  <header className="topbar"><button className="brand" aria-label="Главное меню" onClick={()=>{if(mode==='menu')return;setModal('settings');}}><span className="brand-symbol"><RadioTower size={22}/></span><span>LAST SIGNAL<span className="brand-sub">ORBITAL OPERATIONS</span></span></button>
   {mode==='menu'?<div className="build-tag"><span className="line-dot"/> CO-OP EXPEDITION <span className="tag-divider">/</span> 01</div>:<div className="run-clock"><span>{state.phase==='lobby'?'ПОДГОТОВКА':ended?'ЭКСПЕДИЦИЯ ЗАВЕРШЕНА':`ВОЛНА ${state.wave.toString().padStart(2,'0')}`}</span><strong>{timeText(state.t)}</strong></div>}
   <div className="top-actions"><button className="icon-btn" aria-label={volume?'Выключить звук':'Включить звук'} title="Звук" onClick={()=>{audio.current?.unlock();setVolume(volume?0:35);}}>{volume?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className="icon-btn fullscreen-btn" aria-label={full?'Выйти из полноэкранного режима':'На весь экран'} onClick={fullscreen}>{full?<Minimize2 size={19}/>:<Maximize2 size={19}/>}</button><button className="icon-btn" aria-label="Настройки" onClick={()=>setModal('settings')}><Settings2 size={19}/></button></div>
  </header>
  {mode==='menu'&&<>
   <section className="main-menu"><div className="eyebrow"><span/> СИГНАЛ БЕДСТВИЯ ПОЛУЧЕН</div><h1>LAST<br/>SIGNAL<span className="title-dot">.</span></h1><div className="title-translation">ПОСЛЕДНИЙ СИГНАЛ</div><p className="intro">Станция замолчала.<br/>Вы — её последний шанс.</p>
    <div className="menu-controls"><Button className="deploy-button" disabled={!ready} onClick={startSolo}>{ready?<><span><Play size={17} fill="currentColor"/> НАЧАТЬ ЭКСПЕДИЦИЮ</span><ArrowUpRight size={23}/></>:<><LoaderCircle className="spin" size={19}/> ЗАГРУЗКА СТАНЦИИ</>}</Button><div className="coop-buttons"><Button variant="outline" disabled={!ready} onClick={()=>{setError('');setModal('create');}}><Users size={17}/> Создать отряд</Button><Button variant="outline" disabled={!ready} onClick={()=>{setError('');setModal('join');}}><Link2 size={17}/> Войти по коду</Button></div><div className="mode-caption"><span>Соло или команда до 4 игроков</span><button onClick={()=>setModal('help')}>Как играть <ArrowRight size={13}/></button></div></div>
   </section>
   <aside className="station-caption"><span>СЕКТОР 04 / ОРБИТА ТАУ</span><strong>КЕПЛЕР–09</strong><div><i/> СВЯЗЬ ПРЕРВАНА</div></aside>
   <footer className="menu-footer"><div className="mission-brief"><span className="brief-number">01<span>/</span></span><div><span className="eyebrow subtle">ТЕКУЩАЯ ОПЕРАЦИЯ</span><h2>Вернуть свет</h2><p>Три модуля. Один сигнал. Весь отряд.</p></div><span className="brief-icon"><RadioTower size={28}/></span></div><div className="footer-meta"><button onClick={()=>setModal('roadmap')}>ПЛАН РАЗВИТИЯ <ArrowUpRight size={13}/></button><span>ПЕРВАЯ ИГРОВАЯ ВЕРСИЯ · 0.1</span></div></footer>
  </>}
  {mode!=='menu'&&<>
   {running&&<section className="objective-panel"><div className="eyebrow subtle">ОПЕРАЦИЯ / ВЕРНУТЬ СВЕТ</div><h2>{state.phase==='extract'?'Доберитесь до эвакуации':'Восстановите энергомодули'}</h2><p>{state.phase==='extract'?(state.extraction>0?`Транспорт прибудет через ${Math.ceil(state.extraction)} сек.`:'Соберите выживших в зоне EVAC.'): 'Подойдите к модулю и удерживайте E.'}</p><div className="relay-list">{state.relays.map(r=><div key={r.label} className={`relay-item ${r.active?'complete':''}`}><span>{r.active?<Check size={14}/>:r.label}</span><Progress value={r.charge} aria-label={`Модуль ${r.label}: ${Math.round(r.charge)}%`}/></div>)}</div><div className="core-status"><Shield size={13}/><span>Реактор</span><Progress value={state.core} aria-label="Прочность реактора"/><b>{Math.ceil(state.core)}%</b></div></section>}
   <aside className="squad-panel"><div className="squad-label"><span>{mode==='solo'?'ОДИНОЧНАЯ ЭКСПЕДИЦИЯ':`ОТРЯД / ${session?.code}`}</span>{mode==='online'&&<button aria-label="Скопировать приглашение" onClick={copyInvite}>{copied?<Check size={14}/>:<Copy size={14}/>}</button>}</div>{state.players.map(p=><div key={p.id} className={`squad-member ${p.hp<=0?'is-downed':''}`}><span className="member-index" style={{color:COLORS[p.slot]}}>0{p.slot+1}</span><div><strong>{p.name}{p.id===myId.current&&<small>ВЫ</small>}</strong><span>{!p.connected?'Переподключается':p.hp<=0?`Ранен · ${Math.ceil(p.down)} с`:ROLE_NAMES[p.role]}</span></div><div className="member-health"><HeartPulse size={13}/>{Math.ceil(p.hp)}</div></div>)}{mode==='online'&&<div className={`connection-state ${status!=='online'?'warn':''}`}><i/>{status==='online'?`${ping} мс · связь установлена`:status==='connecting'?'Подключение…':status==='reconnecting'?'Восстанавливаем связь…':'Связь потеряна'}</div>}</aside>
   {state.phase==='lobby'&&<section className="lobby-panel"><div className="eyebrow"><Users size={15}/> ПОДГОТОВКА ОТРЯДА</div><h2>Никого не оставляем.</h2><p>Передайте код напарникам. Командир запускает экспедицию, когда все готовы.</p><button className="room-code" onClick={copyInvite} title="Скопировать приглашение">{session?.code} {copied?<Check size={19}/>:<Copy size={19}/>}</button><div className="lobby-count">{state.players.filter(p=>p.connected).length} / 4 игроков в отряде</div><Button className="deploy-button" disabled={!isHost||status!=='online'} onClick={()=>{audio.current?.unlock();connection.current?.request('start');}}>{isHost?'НАЧАТЬ МИССИЮ':'ОЖИДАЕМ КОМАНДИРА'}<ArrowUpRight size={21}/></Button><button className="text-button" onClick={exitMission}>Покинуть отряд</button></section>}
   {running&&localPlayer&&<><div className="bottom-hud"><div className="vitals"><div className="vital-icon"><HeartPulse size={21}/></div><div className="vitals-main"><div><strong>{Math.ceil(localPlayer.hp)}</strong><span>/ 100</span><small>{ROLE_NAMES[localPlayer.role]}</small></div><Progress value={localPlayer.hp} aria-label="Ваше здоровье"/></div></div><div className="ammo"><Crosshair size={20}/><strong>{localPlayer.ammo.toString().padStart(2,'0')}</strong><span>/ 24<small>{localPlayer.reload>0?'ПЕРЕЗАРЯДКА':'R · ПЕРЕЗАРЯДИТЬ'}</small></span></div><div className="ability"><kbd>Q</kbd><div><strong>{localPlayer.skillCd>0?`${Math.ceil(localPlayer.skillCd)} СЕК`:localPlayer.role==='assault'?'ПЕРЕГРУЗКА':localPlayer.role==='medic'?'ЛЕЧЕНИЕ':'ИМПУЛЬС'}</strong><span>{localPlayer.skillCd>0?'Восстанавливается':'Способность готова'}</span></div></div><div className="dash"><kbd>SPACE</kbd><span>{localPlayer.dashCd>0?`${localPlayer.dashCd.toFixed(1)} с`:'РЫВОК'}</span></div></div>
    <div className="control-strip"><span><kbd>W A S D</kbd> движение</span><span><kbd>ЛКМ</kbd> огонь</span><span><kbd>E</kbd> взаимодействие</span><button onClick={()=>setModal('help')}><CircleHelp size={14}/> управление</button></div>
    {contextAction(state,localPlayer)&&<div className="interaction-prompt"><kbd>E</kbd>{localPlayer.hp<=0?'Вы ранены. Напарник может вас поднять.':contextAction(state,localPlayer).replace('Удерживайте E · ','')}<span>{localPlayer.hp<=0?`${Math.ceil(localPlayer.down)} с`:'УДЕРЖИВАЙТЕ'}</span></div>}
    {state.phase==='extract'&&state.extraction<=0&&<div className="evac-message"><RadioTower size={17}/>{state.extractHold>0?`ЭВАКУАЦИЯ · ${Math.ceil(3-state.extractHold)}`:'ТРАНСПОРТ ПРИБЫЛ · СОБЕРИТЕСЬ В ЗОНЕ EVAC'}</div>}
   </>}
   {ended&&<section className={`result-panel ${state.phase==='won'?'victory':'defeat'}`}><div className="result-icon">{state.phase==='won'?<RadioTower size={35}/>:<Zap size={35}/>}</div><div className="eyebrow">{state.phase==='won'?'ОПЕРАЦИЯ ЗАВЕРШЕНА':'СИГНАЛ ПРЕРВАН'}</div><h2>{state.phase==='won'?'Вы вернулись.':'Тишина на орбите.'}</h2><p>{state.result}</p><div className="result-stats"><div><strong>{timeText(state.t)}</strong><span>ВРЕМЯ МИССИИ</span></div><div><strong>{state.players.reduce((a,p)=>a+p.kills,0)}</strong><span>ДРОНОВ УНИЧТОЖЕНО</span></div><div><strong>{completed} / 3</strong><span>МОДУЛЕЙ ЗАПУЩЕНО</span></div></div><Button className="deploy-button" disabled={mode==='online'&&!isHost} onClick={restart}><RotateCcw size={18}/>{mode==='online'&&!isHost?'ОЖИДАЕМ КОМАНДИРА':'ЕЩЁ ОДНА ЭКСПЕДИЦИЯ'}<ArrowRight size={19}/></Button><button className="text-button" onClick={exitMission}>Вернуться в меню</button></section>}
   {error&&<div className="network-error" role="alert">{error}{status==='offline'&&<button onClick={exitMission}>В меню</button>}</div>}
  </>}
  {renderError&&<div className="fatal-error" role="alert"><Zap size={24}/><p>{renderError}</p><Button onClick={()=>location.reload()}>Обновить страницу</Button></div>}
  {touchUi&&running&&!modal&&<div className="touch-controls"><div className="joystick" aria-label="Джойстик движения" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);updateStick(e,touch.current);}} onPointerMove={e=>{if(e.buttons)updateStick(e,touch.current);}} onPointerUp={()=>{touch.current.x=0;touch.current.z=0;}} onPointerCancel={()=>{touch.current.x=0;touch.current.z=0;}}><Crosshair size={28}/></div><div className="touch-buttons"><button onPointerDown={()=>touchKey('KeyQ',true)} onPointerUp={()=>touchKey('KeyQ',false)} onPointerCancel={()=>touchKey('KeyQ',false)}>Q</button><button onPointerDown={()=>touchKey('Space',true)} onPointerUp={()=>touchKey('Space',false)} onPointerCancel={()=>touchKey('Space',false)}>Рывок</button><button onPointerDown={()=>touchKey('KeyE',true)} onPointerUp={()=>touchKey('KeyE',false)} onPointerCancel={()=>touchKey('KeyE',false)}>E</button><button className="touch-fire" onPointerDown={()=>{touch.current.fire=true;audio.current?.unlock();}} onPointerUp={()=>{touch.current.fire=false;input.current.fire=false;}} onPointerCancel={()=>{touch.current.fire=false;input.current.fire=false;}}><Crosshair size={24}/></button></div></div>}
  {toast&&<div className="toast" role="status">{toast}</div>}
  <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null);}}><DialogContent className={`game-dialog ${modal==='roadmap'?'roadmap-dialog':''}`}>
   <DialogTitle>{modal==='settings'?'Настройки':modal==='help'?'Руководство отряда':modal==='create'?'Собрать отряд':modal==='join'?'Присоединиться': 'План развития LAST SIGNAL'}</DialogTitle>
   <DialogDescription>{modal==='settings'?(mode==='solo'?'Игра приостановлена.':mode==='online'?'Сетевая миссия продолжается.':'Настройте игру под себя.'):modal==='help'?'Восстановите три модуля, защитите реактор и эвакуируйтесь.':modal==='roadmap'?'От первой законченной миссии к полноценной кооперативной игре.':'Выберите позывной и специализацию перед экспедицией.'}</DialogDescription>
   {(modal==='create'||modal==='join')&&<form onSubmit={e=>{e.preventDefault();void connectRoom(modal==='join');}} className="room-form"><label htmlFor="pilot-name">Ваш позывной</label><TextInput id="pilot-name" value={name} onChange={e=>setName(e.target.value)} maxLength={18} placeholder="Например, ICE" autoComplete="off" required/>{modal==='join'&&<><label htmlFor="room-code">Код отряда</label><TextInput id="room-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6))} maxLength={6} minLength={6} pattern="[A-Z2-9]{6}" placeholder="ABC234" className="code-input" required autoComplete="off"/></>}<label>Специализация</label><RolePicker role={role} onChange={setRole}/>{error&&<p className="form-error" role="alert">{error}</p>}<Button className="deploy-button" type="submit" disabled={busy||!ready}>{busy?<><LoaderCircle className="spin" size={18}/> СОЕДИНЯЕМСЯ…</>:<>{modal==='join'?'ВОЙТИ В ОТРЯД':'СОЗДАТЬ КОМНАТУ'}<ArrowUpRight size={21}/></>}</Button></form>}
   {modal==='settings'&&<div className="settings-content"><div className="setting-row"><label>Громкость</label><span>{volume}%</span></div><Slider aria-label="Громкость" value={[volume]} onValueChange={v=>{audio.current?.unlock();setVolume(v[0]);}} min={0} max={100} step={5}/><div className="setting-row"><label>Графика</label></div><RadioGroup value={quality} onValueChange={setQuality} className="quality-options"><label><RadioGroupItem value="high"/> Высокая</label><label><RadioGroupItem value="low"/> Производительность</label></RadioGroup><div className="setting-row"><label htmlFor="motion-setting">Уменьшить движение и тряску</label><Switch id="motion-setting" checked={reduceMotion} onCheckedChange={setReduceMotion}/></div>{mode==='menu'&&<><div className="setting-row"><label>Специализация в соло</label></div><RolePicker role={role} onChange={setRole}/></>}<Button className="deploy-button" onClick={()=>setModal(null)}>{mode==='menu'?'ГОТОВО':'ПРОДОЛЖИТЬ'}<ArrowRight size={20}/></Button>{mode!=='menu'&&<button className="text-button leave-button" onClick={exitMission}><LogOut size={16}/> Покинуть экспедицию</button>}</div>}
   {modal==='help'&&<div className="help-content"><div className="help-mission"><span>01</span><p><strong>Верните питание.</strong> Подойдите к каждому модулю и удерживайте E. Инженер чинит быстрее, несколько игроков могут помогать одновременно.</p></div><div className="help-mission"><span>02</span><p><strong>Прикрывайте напарников.</strong> Не позволяйте дронам разрушить центральный реактор. Поднимайте раненых клавишей E и подбирайте зелёные аптечки.</p></div><div className="help-mission"><span>03</span><p><strong>Вернитесь домой.</strong> После запуска трёх модулей продержитесь 32 секунды. Затем соберите выживших в зоне EVAC на 3 секунды.</p></div><div className="help-keys">{[['W A S D','Движение'],['МЫШЬ','Прицеливание'],['ЛКМ','Стрельба'],['SPACE','Рывок'],['E','Ремонт / помощь'],['R','Перезарядка'],['Q','Способность'],['ESC','Настройки']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div><p className="help-footnote">На сенсорном экране: джойстик слева, огонь и действия справа. При стрельбе прицел автоматически выбирает ближайшего дрона.</p></div>}
   {modal==='roadmap'&&<div className="roadmap-content">{[['01','Первая игровая версия','СЕЙЧАС','Одна станция, три роли, три типа врагов, ремонт, помощь напарникам и эвакуация. Соло и комнаты до 4 игроков.'],['02','Проверка на игроках','СЛЕДУЮЩИЙ ЭТАП','Совместные прохождения, настройка сложности и темпа, проверка задержек и обрывов связи на реальных устройствах.'],['03','Расширение игры','ЗАПЛАНИРОВАНО','Новые станции, особые противники, оружие и выбор улучшений между экспедициями.'],['04','Подготовка к релизу','ЗАПЛАНИРОВАНО','Выделенные игровые сессии, нагрузочные испытания, подбор игроков, профили и долгосрочное развитие.']].map(([n,title,badge,desc])=><div className="roadmap-step" key={n}><span>{n}</span><div><small>{badge}</small><h3>{title}</h3><p>{desc}</p></div></div>)}<p className="help-footnote">Версия 0.1 — основа для развития. Производительность под массовой нагрузкой и совместимость на разных устройствах ещё нужно проверить.</p></div>}
  </DialogContent></Dialog>
 </main>;
}
function performanceNow(){return typeof performance!=='undefined'?performance.now():0;}
function RolePicker({role,onChange}:{role:Role;onChange:(role:Role)=>void}){return <RadioGroup value={role} onValueChange={v=>onChange(v as Role)} className="role-picker">{roles.map(([r,Icon,perk,ability])=><label key={r} className={role===r?'selected':''}><RadioGroupItem value={r} className="role-radio"/><Icon size={23}/><strong>{ROLE_NAMES[r]}</strong><span>{perk}</span><small>{ability}</small></label>)}</RadioGroup>;}
function updateStick(e:React.PointerEvent<HTMLDivElement>,stick:{x:number;z:number}){const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)/(r.width*.4),z=(e.clientY-r.top-r.height/2)/(r.height*.4),len=Math.max(1,Math.hypot(x,z));stick.x=x/len;stick.z=z/len;}
function drawOverlay(canvas:HTMLCanvasElement|null,renderer:GameRenderer,s:State,id:string,playing:boolean,pointer:{x:number;y:number;set:boolean},modal:boolean){if(!canvas)return;const dpr=Math.min(devicePixelRatio,2),w=renderer.width,h=renderer.height;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}const ctx=canvas.getContext('2d')!;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!playing)return;
 for(const p of s.players){const pos=renderer.screenPosition(p.x,p.z,2.3);if(!p.connected)continue;ctx.font='600 12px Arial';ctx.textAlign='center';ctx.fillStyle=p.hp<=0?'#ff976f':COLORS[p.slot];ctx.shadowColor='#030a0d';ctx.shadowBlur=4;ctx.fillText(p.id===id?'ВЫ':p.name,pos.x,pos.y);ctx.shadowBlur=0;if(p.hp<=0){ctx.fillStyle='#142123';ctx.fillRect(pos.x-20,pos.y+7,40,4);ctx.fillStyle='#b6f06b';ctx.fillRect(pos.x-20,pos.y+7,40*p.revive,4);}}
 for(const e of s.enemies){if(e.hp===e.maxHp)continue;const pos=renderer.screenPosition(e.x,e.z,e.kind==='brute'?2.2:1.7);ctx.fillStyle='#170f11';ctx.fillRect(pos.x-13,pos.y,26,3);ctx.fillStyle='#ff9b72';ctx.fillRect(pos.x-13,pos.y,26*Math.max(0,e.hp/e.maxHp),3);}
 const p=s.players.find(p=>p.id===id);for(const r of s.relays){if(r.active)continue;const pos=renderer.screenPosition(r.x,r.z,3.2);const near=p&&Math.hypot(r.x-p.x,r.z-p.z)<2.8;ctx.font='600 12px Arial';ctx.textAlign='center';ctx.fillStyle=near?'#e5f4d2':'#e4b971';ctx.fillText(`МОДУЛЬ ${r.label}${r.charge>0?' · '+Math.floor(r.charge)+'%':''}`,pos.x,pos.y);}
 if(s.phase==='extract'){const pos=renderer.screenPosition(EXTRACTION.x,EXTRACTION.z,2);ctx.fillStyle='#b6f06b';ctx.font='700 14px Arial';ctx.textAlign='center';ctx.fillText(s.extraction>0?`EVAC · ${Math.ceil(s.extraction)} с`:'ЭВАКУАЦИЯ',pos.x,pos.y);}
 if(pointer.set&&!modal&&p&&p.hp>0){const rect=canvas.getBoundingClientRect(),x=pointer.x-rect.left,y=pointer.y-rect.top;ctx.strokeStyle='#c8f3d3';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.moveTo(x-11,y);ctx.lineTo(x-8,y);ctx.moveTo(x+8,y);ctx.lineTo(x+11,y);ctx.moveTo(x,y-11);ctx.lineTo(x,y-8);ctx.moveTo(x,y+8);ctx.lineTo(x,y+11);ctx.stroke();}
 if(p&&p.hp<30){const gradient=ctx.createRadialGradient(w/2,h/2,h*.25,w/2,h/2,w*.7);gradient.addColorStop(0,'transparent');gradient.addColorStop(1,'rgba(170,45,26,.22)');ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);}
}
